---
name: 'deploy'

'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  forge_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/puppet-forge-deploy.yml@tex_puppet_deploy
